### ISSUE TITLE
Confirm same issue?

### ISSUE THREAD

**Issue by TimothyGillespie** [JavaWebStack/ORM#12]
As I was writing tests I ran into the following issue:
When checking a class' simple name I got the class name with an extra s. You can see this on this branch: TimothyGillespie/testFromClauses

With the test src/test/java/org/javawebstack/orm/test/querybuilding/FromClauseTest - testOneWordSAppendixPlural()

Can anyone reproduce that the System.out.println() on line 24 also returns `words`? Is this supposed to be like this? I didn't find anything in the documentation.

**Comment by JulianFun123** [comment]
```java
System.out.println(English.plural(Word.class.getSimpleName()));
```
Yes... probably unsuspected behavior

**Comment by TimothyGillespie** [comment]
Yeah, I'm stupid. Four eyes see more, thanks.
