### ISSUE TITLE
Explicitly use ASC in SQL syntax when using order()

### ISSUE THREAD

**Issue by TimothyGillespie** [JavaWebStack/ORM#23]
I would suggest always adding the ASC explicitly in the SQL query. I am not aware of any SQL dialect which uses the DESC declaration or requires the ASC decleration, but it seems cleaner to me.

Any thoughts on this?

**Comment by JanHolger** [comment]
With the abstraction of the query generation in the maintenance branch we shift to different generators per dialect so this won't be an issue. Adding the ASC explicitly would add 4 unnecessary extra bytes per query. The ORM is supposed to abstract away the database anyway so in the best case a user will never see the query.

**Comment by TimothyGillespie** [comment]
4 bytes are not a lot but I guess if the query is still unambiguous, then I can agree with this. I will adjust #21 accordingly.
