### ISSUE TITLE
update

### ISSUE THREAD

**Issue by x7airworker** [JavaWebStack/ORM#33]
**Is your feature request related to a problem? Please describe.**
There should be an `update(String column, Object value)` method, which allows to update every row to this value.
Example use case would be to null a column, if a member of a relation gets deleted, instead of deleting the other entry too.

**Describe the solution you'd like**
- New Method `update(String column, Object value)`

**Describe alternatives you've considered**
Currently I am doing the following:
```java
user.hasMany(Todo.class, "userId").all().forEach(t -> {
    t.setUserId(0);
    t.save();
});
```

**Comment by JulianFun123** [comment]
You could use Query#update(Map<String, Object> values) for what you want or do I not understand your question?

**Comment by x7airworker** [comment]
> You could use Query#update(Map<String, Object> values) for what you want or do I not understand your question?

Maybe I didn't understand the parameter right, is it a column -> value mapping? So I could put in A map with "userId" and 0 in it?

**Comment by JulianFun123** [comment]
Yes. For example
```java
Map<String, Object> update = new HashMap<>();
update.put("userId", 0);
Repo.get(Todo.class).where("userId", userId).update(update);
```
