### ISSUE TITLE
Setting a size on a field with an enum type leads to SQL syntax error

### ISSUE THREAD

**Issue by x7airworker** [JavaWebStack/ORM#38]
**To Reproduce**
```java
public class Example extends Model {
   @Column
    UUID id;
   @Column(size = 255)
    Type type; // Type is an enum
}
```

**Expected behavior**
Instead of generating a varchar with enum values, it should make the column a varchar with the supplied size

**Screenshots / Logs**
```sql
VARCHAR('enum_value_1', 'enum_value_2')
```
**Environment Information:**
 - Java Language Level 8
 - Version 1.0.2-SNAPSHOT

**Comment by JanHolger** [comment]
fixed with 9f73d833a818162cb3a9929082679ddb78a5c05a
