### ISSUE TITLE
Support for Indexes

### ISSUE THREAD

**Issue by x7airworker** [JavaWebStack/ORM#42]
**Is your feature request related to a problem? Please describe.**
Currently we have no ability to set Indexes in the auto migration.

**Describe the solution you'd like**
The `@Column` annotation should have a boolean parameter `index` which by default is set to `false`.

**Comment by JWaldecker** [comment]
From my view it could be better to add a `@Index` annotation to the class itself where a list of the columns included in the index can be defined. Otherwise it would not be possible to handle an index containing more than one column. What do you think about it?

**Comment by x7airworker** [comment]
This sounds like a good approach. We should make the `@Index` annotation repeatable so we can create multiple indexes with multiple columns.
